"""empty message

Revision ID: 010666fea308
Revises: ff4a7a06222e
Create Date: 2025-12-08 17:03:38.479517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '010666fea308'
down_revision = 'ff4a7a06222e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('need_stamp', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('expire_time', mysql.DATETIME(fsp=0), nullable=True))
        batch_op.add_column(sa.Column('final_doc_relpath', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('final_doc_relpath')
        batch_op.drop_column('expire_time')
        batch_op.drop_column('need_stamp')
        batch_op.drop_column('doc_name')

    # ### end Alembic commands ###
