"""empty message

Revision ID: 0338dc092ac5
Revises: 167971f82dbb
Create Date: 2025-10-11 23:23:31.565242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0338dc092ac5'
down_revision = '167971f82dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eink_device',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('panel_res', sa.String(length=16), nullable=False),
    sa.Column('bpp', sa.Integer(), nullable=False),
    sa.Column('cap', sa.String(length=16), nullable=False),
    sa.Column('supports_partial', sa.Boolean(), nullable=False),
    sa.Column('supports_rle', sa.Boolean(), nullable=False),
    sa.Column('supports_zlib', sa.Boolean(), nullable=False),
    sa.Column('current_ver', sa.BigInteger(), nullable=False),
    sa.Column('last_seen', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_eink_device_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eink_device')),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_eink_device_user_device'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eink_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eink_device_user_id'), ['user_id'], unique=False)

    op.create_table('eink_asset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('upload_id', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('bpp', sa.Integer(), nullable=False),
    sa.Column('ver', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('bin_relpath', sa.String(length=512), nullable=False),
    sa.Column('meta_relpath', sa.String(length=512), nullable=False),
    sa.Column('raw_len', sa.Integer(), nullable=False),
    sa.Column('total_len', sa.Integer(), nullable=False),
    sa.Column('crc32_le', sa.String(length=8), nullable=False),
    sa.Column('asset_partial_ready', sa.Boolean(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('expect_post_time', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('posting_period_sec', sa.Integer(), nullable=True),
    sa.Column('expire_time', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('need_approval', sa.Boolean(), nullable=False),
    sa.Column('final_approval', sa.Boolean(), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.CheckConstraint('height > 0', name='ck_easset_height_pos'),
    sa.CheckConstraint('raw_len   > 0', name='ck_easset_rawlen_pos'),
    sa.CheckConstraint('total_len > 0', name='ck_easset_totallen_pos'),
    sa.CheckConstraint('width  > 0', name='ck_easset_width_pos'),
    sa.ForeignKeyConstraint(['route_id'], ['approval_routes.id'], name=op.f('fk_eink_asset_route_id_approval_routes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_eink_asset_upload_id_uploads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_eink_asset_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eink_asset')),
    sa.UniqueConstraint('user_id', 'device_id', 'ver', name='uq_easset_user_dev_ver'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eink_asset', schema=None) as batch_op:
        batch_op.create_index('idx_easset_sched', ['user_id', 'device_id', 'expect_post_time', 'expire_time'], unique=False)
        batch_op.create_index('idx_easset_user_dev_ver', ['user_id', 'device_id', 'ver'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_asset_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_asset_user_id'), ['user_id'], unique=False)

    op.create_table('eink_posting',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'active', 'expired', 'canceled', 'failed', name='eink_posting_status'), nullable=False),
    sa.Column('start_time', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('end_time', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.CheckConstraint('(end_time IS NULL) OR (start_time IS NULL) OR (start_time < end_time)', name='ck_eposting_time_range'),
    sa.ForeignKeyConstraint(['asset_id'], ['eink_asset.id'], name=op.f('fk_eink_posting_asset_id_eink_asset'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_eink_posting_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eink_posting')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eink_posting', schema=None) as batch_op:
        batch_op.create_index('idx_eposting_window', ['user_id', 'device_id', 'start_time', 'end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_posting_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_posting_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_posting_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index('idx_upload_queue', ['user_id', 'target_dir', 'status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index('idx_upload_queue')

    with op.batch_alter_table('eink_posting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eink_posting_user_id'))
        batch_op.drop_index(batch_op.f('ix_eink_posting_device_id'))
        batch_op.drop_index(batch_op.f('ix_eink_posting_asset_id'))
        batch_op.drop_index('idx_eposting_window')

    op.drop_table('eink_posting')
    with op.batch_alter_table('eink_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eink_asset_user_id'))
        batch_op.drop_index(batch_op.f('ix_eink_asset_device_id'))
        batch_op.drop_index('idx_easset_user_dev_ver')
        batch_op.drop_index('idx_easset_sched')

    op.drop_table('eink_asset')
    with op.batch_alter_table('eink_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eink_device_user_id'))

    op.drop_table('eink_device')
    # ### end Alembic commands ###
