"""empty message

Revision ID: 0d851f75b114
Revises: b138224212e2
Create Date: 2025-01-21 13:22:09.351716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d851f75b114'
down_revision = 'b138224212e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImageData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star_name', sa.String(length=100), nullable=False),
    sa.Column('type_image', sa.String(length=100), nullable=False),
    sa.Column('title_image', sa.String(length=300), nullable=False),
    sa.Column('json_file', sa.String(length=200), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('sizewidth', sa.String(length=100), nullable=False),
    sa.Column('sizeheight', sa.String(length=100), nullable=False),
    sa.Column('update_date', sa.String(length=150), nullable=False),
    sa.Column('view_count', sa.String(length=100), nullable=True),
    sa.Column('favorite_count', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ImageData'))
    )
    op.drop_table('NaverData')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NaverData',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('star_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type_image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title_image', sa.VARCHAR(length=300), nullable=False),
    sa.Column('json_file', sa.VARCHAR(length=200), nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('update_date', sa.VARCHAR(length=150), nullable=False),
    sa.Column('view_count', sa.VARCHAR(length=100), nullable=True),
    sa.Column('favorite_count', sa.VARCHAR(length=100), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=500), nullable=False),
    sa.Column('sizeheight', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sizewidth', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ImageData')
    # ### end Alembic commands ###
