"""uploads: enum -> varchar + check

Revision ID: 167971f82dbb
Revises: 451a008a902d
Create Date: 2025-10-11 00:38:59.107250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '167971f82dbb'
down_revision = '451a008a902d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.alter_column('target_dir',
               existing_type=mysql.ENUM('uploads', 'proceed', 'checked', 'updates'),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'proceed'"))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('draft', 'in_review', 'checked', 'approved', 'rejected'),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=16),
               type_=mysql.ENUM('draft', 'in_review', 'checked', 'approved', 'rejected'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('target_dir',
               existing_type=sa.String(length=16),
               type_=mysql.ENUM('uploads', 'proceed', 'checked', 'updates'),
               existing_nullable=False,
               existing_server_default=sa.text("'proceed'"))

    # ### end Alembic commands ###
