"""initial schema

Revision ID: 28cfda66f072
Revises: 
Create Date: 2025-10-02 09:57:54.101513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28cfda66f072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('userimage', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=150), nullable=False),
    sa.Column('photo_1', sa.String(length=500), nullable=True),
    sa.Column('photo_2', sa.String(length=500), nullable=True),
    sa.Column('photo_3', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('com_address', sa.String(length=500), nullable=True),
    sa.Column('tel_rep', sa.String(length=100), nullable=True),
    sa.Column('tel_dir', sa.String(length=100), nullable=True),
    sa.Column('fax', sa.String(length=100), nullable=True),
    sa.Column('homepage', sa.String(length=300), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('blood', sa.String(length=150), nullable=True),
    sa.Column('healthy', sa.String(length=150), nullable=True),
    sa.Column('age', sa.String(length=150), nullable=True),
    sa.Column('namecard', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('security', sa.String(length=100), nullable=False),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.PrimaryKeyConstraint('no', name=op.f('pk_user')),
    sa.UniqueConstraint('userid', name=op.f('uq_user_userid')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_authorization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_authorization')),
    sa.UniqueConstraint('email', name=op.f('uq_user_authorization_email')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vehicle_usage',
    sa.Column('no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_no', sa.String(length=150), nullable=False),
    sa.Column('car_name', sa.String(length=150), nullable=False),
    sa.Column('car_fuel', sa.String(length=150), nullable=False),
    sa.Column('use_year', sa.String(length=150), nullable=False),
    sa.Column('acum_ref', sa.String(length=150), nullable=False),
    sa.Column('acum_jan', sa.String(length=150), nullable=True),
    sa.Column('use_jan', sa.String(length=150), nullable=True),
    sa.Column('acum_feb', sa.String(length=150), nullable=True),
    sa.Column('use_feb', sa.String(length=150), nullable=True),
    sa.Column('acum_mar', sa.String(length=150), nullable=True),
    sa.Column('use_mar', sa.String(length=150), nullable=True),
    sa.Column('acum_apr', sa.String(length=150), nullable=True),
    sa.Column('use_apr', sa.String(length=150), nullable=True),
    sa.Column('acum_may', sa.String(length=150), nullable=True),
    sa.Column('use_may', sa.String(length=150), nullable=True),
    sa.Column('acum_jun', sa.String(length=150), nullable=True),
    sa.Column('use_jun', sa.String(length=150), nullable=True),
    sa.Column('acum_jul', sa.String(length=150), nullable=True),
    sa.Column('use_jul', sa.String(length=150), nullable=True),
    sa.Column('acum_aug', sa.String(length=150), nullable=True),
    sa.Column('use_aug', sa.String(length=150), nullable=True),
    sa.Column('acum_sep', sa.String(length=150), nullable=True),
    sa.Column('use_sep', sa.String(length=150), nullable=True),
    sa.Column('acum_oct', sa.String(length=150), nullable=True),
    sa.Column('use_oct', sa.String(length=150), nullable=True),
    sa.Column('acum_nov', sa.String(length=150), nullable=True),
    sa.Column('use_nov', sa.String(length=150), nullable=True),
    sa.Column('acum_dec', sa.String(length=150), nullable=True),
    sa.Column('use_dec', sa.String(length=150), nullable=True),
    sa.Column('total', sa.String(length=150), nullable=True),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=True),
    sa.PrimaryKeyConstraint('no', name=op.f('pk_vehicle_usage')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('water_usage',
    sa.Column('no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_no', sa.String(length=150), nullable=False),
    sa.Column('use_year', sa.String(length=150), nullable=False),
    sa.Column('acum_ref', sa.String(length=150), nullable=False),
    sa.Column('acum_jan', sa.String(length=150), nullable=True),
    sa.Column('use_jan', sa.String(length=150), nullable=True),
    sa.Column('acum_feb', sa.String(length=150), nullable=True),
    sa.Column('use_feb', sa.String(length=150), nullable=True),
    sa.Column('acum_mar', sa.String(length=150), nullable=True),
    sa.Column('use_mar', sa.String(length=150), nullable=True),
    sa.Column('acum_apr', sa.String(length=150), nullable=True),
    sa.Column('use_apr', sa.String(length=150), nullable=True),
    sa.Column('acum_may', sa.String(length=150), nullable=True),
    sa.Column('use_may', sa.String(length=150), nullable=True),
    sa.Column('acum_jun', sa.String(length=150), nullable=True),
    sa.Column('use_jun', sa.String(length=150), nullable=True),
    sa.Column('acum_jul', sa.String(length=150), nullable=True),
    sa.Column('use_jul', sa.String(length=150), nullable=True),
    sa.Column('acum_aug', sa.String(length=150), nullable=True),
    sa.Column('use_aug', sa.String(length=150), nullable=True),
    sa.Column('acum_sep', sa.String(length=150), nullable=True),
    sa.Column('use_sep', sa.String(length=150), nullable=True),
    sa.Column('acum_oct', sa.String(length=150), nullable=True),
    sa.Column('use_oct', sa.String(length=150), nullable=True),
    sa.Column('acum_nov', sa.String(length=150), nullable=True),
    sa.Column('use_nov', sa.String(length=150), nullable=True),
    sa.Column('acum_dec', sa.String(length=150), nullable=True),
    sa.Column('use_dec', sa.String(length=150), nullable=True),
    sa.Column('total', sa.String(length=150), nullable=False),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=True),
    sa.PrimaryKeyConstraint('no', name=op.f('pk_water_usage')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('youtube_url',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star_name', sa.String(length=100), nullable=False),
    sa.Column('type_video', sa.String(length=100), nullable=False),
    sa.Column('title_video', sa.String(length=300), nullable=False),
    sa.Column('json_file', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('update_date', sa.String(length=150), nullable=False),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_url')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('calendar_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.Column('start_time', sa.String(length=150), nullable=True),
    sa.Column('end_time', sa.String(length=150), nullable=True),
    sa.Column('cal_date', sa.String(length=150), nullable=True),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_authorization.id'], name=op.f('fk_calendar_schedule_user_id_user_authorization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_schedule')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fileuploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_1', sa.String(length=255), nullable=True),
    sa.Column('file_2', sa.String(length=255), nullable=True),
    sa.Column('file_3', sa.String(length=255), nullable=True),
    sa.Column('file_4', sa.String(length=255), nullable=True),
    sa.Column('file_5', sa.String(length=255), nullable=True),
    sa.Column('file_6', sa.String(length=255), nullable=True),
    sa.Column('file_7', sa.String(length=255), nullable=True),
    sa.Column('file_8', sa.String(length=255), nullable=True),
    sa.Column('file_9', sa.String(length=255), nullable=True),
    sa.Column('file_10', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_fileuploads_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fileuploads')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('namecard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_photo', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('com_address', sa.String(length=500), nullable=True),
    sa.Column('tel_rep', sa.String(length=100), nullable=True),
    sa.Column('tel_dir', sa.String(length=100), nullable=True),
    sa.Column('fax', sa.String(length=100), nullable=True),
    sa.Column('homepage', sa.String(length=300), nullable=True),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_namecard_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_namecard')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=201), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('user_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_no'], ['user.no'], name=op.f('fk_question_user_no_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_authorization.id'], name=op.f('fk_refresh_token_user_id_user_authorization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token', name=op.f('uq_refresh_token_token')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('user_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_answer_question_id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_no'], ['user.no'], name=op.f('fk_answer_user_no_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('question_voter',
    sa.Column('user_no', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_question_voter_question_id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_no'], ['user.no'], name=op.f('fk_question_voter_user_no_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_no', 'question_id', name='pk_question_voter'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sharecard',
    sa.Column('no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('namecard_id', sa.Integer(), nullable=False),
    sa.Column('fileupload_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('introduce', sa.String(length=500), nullable=True),
    sa.Column('vcf', sa.String(length=150), nullable=True),
    sa.Column('qrcode', sa.String(length=150), nullable=True),
    sa.Column('s_ncard', sa.String(length=150), nullable=False),
    sa.Column('custom_email', sa.String(length=150), nullable=True),
    sa.Column('s_file1', sa.String(length=300), nullable=True),
    sa.Column('s_file2', sa.String(length=300), nullable=True),
    sa.Column('s_file3', sa.String(length=300), nullable=True),
    sa.Column('s_file4', sa.String(length=300), nullable=True),
    sa.Column('s_file5', sa.String(length=300), nullable=True),
    sa.Column('count', sa.String(length=100), nullable=True),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['fileupload_id'], ['fileuploads.id'], name=op.f('fk_sharecard_fileupload_id_fileuploads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['namecard_id'], ['namecard.id'], name=op.f('fk_sharecard_namecard_id_namecard'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_sharecard_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('no', name=op.f('pk_sharecard')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('answer_voter',
    sa.Column('user_no', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name=op.f('fk_answer_voter_answer_id_answer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_no'], ['user.no'], name=op.f('fk_answer_voter_user_no_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_no', 'answer_id', name='pk_answer_voter'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_no', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('modify_date', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name=op.f('fk_comment_answer_id_answer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_comment_question_id_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_no'], ['user.no'], name=op.f('fk_comment_user_no_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('qr_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('namecard_id', sa.Integer(), nullable=False),
    sa.Column('share_card_id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=100), nullable=False),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['namecard_id'], ['namecard.id'], name=op.f('fk_qr_code_namecard_id_namecard'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_card_id'], ['sharecard.no'], name=op.f('fk_qr_code_share_card_id_sharecard'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_qr_code_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_code')),
    sa.UniqueConstraint('unique_id', name='uq_qr_unique_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('welcomedata',
    sa.Column('no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('namecard_id', sa.Integer(), nullable=False),
    sa.Column('share_card_id', sa.Integer(), nullable=False),
    sa.Column('bmp_name', sa.String(length=200), nullable=False),
    sa.Column('bmp_path', sa.String(length=500), nullable=False),
    sa.Column('qr_code', sa.String(length=500), nullable=True),
    sa.Column('unique_id', sa.String(length=150), nullable=True),
    sa.Column('count', sa.String(length=150), nullable=True),
    sa.Column('create_date', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['namecard_id'], ['namecard.id'], name=op.f('fk_welcomedata_namecard_id_namecard'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_card_id'], ['sharecard.no'], name=op.f('fk_welcomedata_share_card_id_sharecard'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_welcomedata_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('no', name=op.f('pk_welcomedata')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('welcomedata')
    op.drop_table('qr_code')
    op.drop_table('comment')
    op.drop_table('answer_voter')
    op.drop_table('sharecard')
    op.drop_table('question_voter')
    op.drop_table('answer')
    op.drop_table('refresh_token')
    op.drop_table('question')
    op.drop_table('namecard')
    op.drop_table('fileuploads')
    op.drop_table('calendar_schedule')
    op.drop_table('youtube_url')
    op.drop_table('water_usage')
    op.drop_table('vehicle_usage')
    op.drop_table('user_authorization')
    op.drop_table('user')
    # ### end Alembic commands ###
