"""empty message

Revision ID: 2ebcd30520fc
Revises: 872cf49fa005
Create Date: 2025-02-11 09:13:36.313211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebcd30520fc'
down_revision = '872cf49fa005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fileuploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_1', sa.String(length=255), nullable=True),
    sa.Column('file_2', sa.String(length=255), nullable=True),
    sa.Column('file_3', sa.String(length=255), nullable=True),
    sa.Column('file_4', sa.String(length=255), nullable=True),
    sa.Column('file_5', sa.String(length=255), nullable=True),
    sa.Column('file_6', sa.String(length=255), nullable=True),
    sa.Column('file_7', sa.String(length=255), nullable=True),
    sa.Column('file_8', sa.String(length=255), nullable=True),
    sa.Column('file_9', sa.String(length=255), nullable=True),
    sa.Column('file_10', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_fileuploads_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fileuploads'))
    )
    op.create_table('sharecard',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('namecard_id', sa.Integer(), nullable=False),
    sa.Column('fileupload_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('introduce', sa.String(length=500), nullable=True),
    sa.Column('vcf', sa.String(length=150), nullable=True),
    sa.Column('qrcode', sa.String(length=150), nullable=True),
    sa.Column('s_ncard', sa.String(length=150), nullable=False),
    sa.Column('custom_email', sa.String(length=150), nullable=True),
    sa.Column('s_file1', sa.String(length=300), nullable=True),
    sa.Column('s_file2', sa.String(length=300), nullable=True),
    sa.Column('s_file3', sa.String(length=300), nullable=True),
    sa.Column('s_file4', sa.String(length=300), nullable=True),
    sa.Column('s_file5', sa.String(length=300), nullable=True),
    sa.Column('count', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modify_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fileupload_id'], ['fileuploads.id'], name=op.f('fk_sharecard_fileupload_id_fileuploads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['namecard_id'], ['namecard.id'], name=op.f('fk_sharecard_namecard_id_namecard'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_sharecard_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('no', name=op.f('pk_sharecard'))
    )
    op.drop_table('file_uploads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('file_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_5', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_6', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_7', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_8', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_9', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_10', sa.VARCHAR(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name='fk_file_uploads_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_file_uploads')
    )
    op.drop_table('sharecard')
    op.drop_table('fileuploads')
    # ### end Alembic commands ###
