"""empty message

Revision ID: 356aeb3a305d
Revises: 365d87a6efa8
Create Date: 2025-02-06 15:53:34.787219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356aeb3a305d'
down_revision = '365d87a6efa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_1', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_3', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('com_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('tel_rep', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tel_dir', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fax', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('homepage', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('namecard', sa.String(length=150), nullable=False))
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=500), nullable=False))
        batch_op.alter_column('company',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.drop_column('namecard')
        batch_op.drop_column('homepage')
        batch_op.drop_column('fax')
        batch_op.drop_column('tel_dir')
        batch_op.drop_column('tel_rep')
        batch_op.drop_column('com_address')
        batch_op.drop_column('photo_3')
        batch_op.drop_column('photo_2')
        batch_op.drop_column('photo_1')

    # ### end Alembic commands ###
