"""empty message

Revision ID: 365d87a6efa8
Revises: 998c57362e63
Create Date: 2025-02-05 10:18:07.749238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365d87a6efa8'
down_revision = '998c57362e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
