"""eink device security fields + asset channel/preview + posting index + accesslog fields

Revision ID: 3c8c714ab992
Revises: b76fcf09845d
Create Date: 2025-12-18 14:35:04.726245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c8c714ab992'
down_revision = 'b76fcf09845d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_access_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('api', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('auth_ok', sa.Boolean(), nullable=False),
    sa.Column('auth_mode', sa.String(length=16), nullable=True),
    sa.Column('device_fp', sa.String(length=64), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.String(length=255), nullable=True),
    sa.Column('posting_id', sa.BigInteger(), nullable=True),
    sa.Column('asset_id', sa.BigInteger(), nullable=True),
    sa.Column('ver', sa.BigInteger(), nullable=True),
    sa.Column('crc32', sa.String(length=8), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_device_access_logs_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_access_logs')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('device_access_logs', schema=None) as batch_op:
        batch_op.create_index('idx_dalog_dev_api_time', ['device_id', 'api', 'created_at'], unique=False)
        batch_op.create_index('idx_dalog_dev_ok_time', ['device_id', 'ok', 'created_at'], unique=False)
        batch_op.create_index('idx_dalog_dev_time', ['device_id', 'created_at'], unique=False)
        batch_op.create_index('idx_dalog_user_dev_time', ['user_id', 'device_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_access_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_access_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('eink_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.Enum('approved', 'bulletin', name='eink_channel'), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_relpath', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('source_kind', sa.Enum('approval_process', 'bulletin_files', name='eink_asset_source_kind'), nullable=True))
        batch_op.add_column(sa.Column('sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=False))
        batch_op.create_index('idx_easset_doc', ['document_info_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_asset_channel'), ['channel'], unique=False)

    with op.batch_alter_table('eink_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_ip', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_user_agent', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_api', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('last_http_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_error_msg', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('expected_wakeup_sec', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wakeup_jitter_sec', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auth_mode', sa.Enum('none', 'hmac', 'mtls', name='eink_device_auth_mode'), nullable=False))
        batch_op.add_column(sa.Column('psk_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('client_cert_fp', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('revoked_at', mysql.DATETIME(fsp=0), nullable=True))
        batch_op.create_index('idx_eink_device_user_lastseen', ['user_no', 'last_seen'], unique=False)

    with op.batch_alter_table('eink_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))
        batch_op.create_index('idx_eposting_lookup', ['user_id', 'device_id', 'status', 'start_time', 'end_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eink_posting', schema=None) as batch_op:
        batch_op.drop_index('idx_eposting_lookup')
        batch_op.drop_column('priority')

    with op.batch_alter_table('eink_device', schema=None) as batch_op:
        batch_op.drop_index('idx_eink_device_user_lastseen')
        batch_op.drop_column('revoked_at')
        batch_op.drop_column('client_cert_fp')
        batch_op.drop_column('psk_hash')
        batch_op.drop_column('auth_mode')
        batch_op.drop_column('wakeup_jitter_sec')
        batch_op.drop_column('expected_wakeup_sec')
        batch_op.drop_column('last_error_msg')
        batch_op.drop_column('last_http_status')
        batch_op.drop_column('last_api')
        batch_op.drop_column('last_user_agent')
        batch_op.drop_column('last_ip')

    with op.batch_alter_table('eink_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eink_asset_channel'))
        batch_op.drop_index('idx_easset_doc')
        batch_op.drop_column('is_encrypted')
        batch_op.drop_column('sha256')
        batch_op.drop_column('source_kind')
        batch_op.drop_column('preview_relpath')
        batch_op.drop_column('title')
        batch_op.drop_column('channel')

    with op.batch_alter_table('device_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_access_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_access_logs_device_id'))
        batch_op.drop_index('idx_dalog_user_dev_time')
        batch_op.drop_index('idx_dalog_dev_time')
        batch_op.drop_index('idx_dalog_dev_ok_time')
        batch_op.drop_index('idx_dalog_dev_api_time')

    op.drop_table('device_access_logs')
    # ### end Alembic commands ###
