"""empty message

Revision ID: 3f1b7fa6e270
Revises: 5bea42e7a4ca
Create Date: 2025-02-10 11:23:32.124300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1b7fa6e270'
down_revision = '5bea42e7a4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_photo', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('com_address', sa.String(length=500), nullable=True),
    sa.Column('tel_rep', sa.String(length=100), nullable=True),
    sa.Column('tel_dir', sa.String(length=100), nullable=True),
    sa.Column('fax', sa.String(length=100), nullable=True),
    sa.Column('homepage', sa.String(length=300), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modify_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_namecard_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_namecard'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('namecard')
    # ### end Alembic commands ###
