"""empty message

Revision ID: 407370418ae1
Revises: 9b2000c85ef0
Create Date: 2025-10-10 14:55:25.474632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '407370418ae1'
down_revision = '9b2000c85ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_route_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_userid_snapshot', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('assignee_username_snapshot', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('assignee_department_snapshot', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('assignee_position_snapshot', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('assignee_photo_1_snapshot', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False))
        batch_op.create_index(batch_op.f('ix_approval_route_steps_assignee_user_id'), ['assignee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_route_steps_route_id'), ['route_id'], unique=False)

    with op.batch_alter_table('approval_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_routes_created_by'), ['created_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_routes_created_by'))

    with op.batch_alter_table('approval_route_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_route_steps_route_id'))
        batch_op.drop_index(batch_op.f('ix_approval_route_steps_assignee_user_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('assignee_photo_1_snapshot')
        batch_op.drop_column('assignee_position_snapshot')
        batch_op.drop_column('assignee_department_snapshot')
        batch_op.drop_column('assignee_username_snapshot')
        batch_op.drop_column('assignee_userid_snapshot')

    # ### end Alembic commands ###
