"""empty message

Revision ID: 4efaa1a98ef4
Revises: bdceb7a19120
Create Date: 2025-10-13 16:39:46.151311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4efaa1a98ef4'
down_revision = 'bdceb7a19120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.BigInteger(), nullable=False),
    sa.Column('slot_key', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.Enum('check', 'photo', name='sign_slot_mode'), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('filled', sa.Boolean(), nullable=False),
    sa.Column('filled_by_id', sa.Integer(), nullable=True),
    sa.Column('filled_at', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['filled_by_id'], ['user.no'], name=op.f('fk_sign_slots_filled_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.no'], name=op.f('fk_sign_slots_target_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_sign_slots_upload_id_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sign_slots')),
    sa.UniqueConstraint('upload_id', 'slot_key', name='uq_signslot_upload_slotkey'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sign_slots', schema=None) as batch_op:
        batch_op.create_index('idx_signslot_upload', ['upload_id', 'filled'], unique=False)
        batch_op.create_index('idx_signslot_user', ['target_user_id', 'filled'], unique=False)
        batch_op.create_index(batch_op.f('ix_sign_slots_upload_id'), ['upload_id'], unique=False)

    op.create_table('upload_approval_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.BigInteger(), nullable=False),
    sa.Column('col_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('작성', '검토', '승인', name='approval_step_type'), nullable=False),
    sa.Column('dept_snapshot', sa.String(length=150), nullable=True),
    sa.Column('userid_snapshot', sa.String(length=150), nullable=True),
    sa.Column('username_snapshot', sa.String(length=150), nullable=True),
    sa.Column('photo_1_snapshot', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'signed', name='approval_sign_status'), nullable=False),
    sa.Column('signed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('signed_at', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('sign_asset_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['signed_by_user_id'], ['user.no'], name=op.f('fk_upload_approval_steps_signed_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_upload_approval_steps_upload_id_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_approval_steps')),
    sa.UniqueConstraint('upload_id', 'col_index', name='uq_uapproval_col'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('upload_approval_steps', schema=None) as batch_op:
        batch_op.create_index('idx_uapproval_upload', ['upload_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_approval_steps_upload_id'), ['upload_id'], unique=False)

    op.create_table('device_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.Enum('full', 'partial', name='device_job_type'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sending', 'done', 'error', name='device_job_status'), nullable=False),
    sa.Column('src_upload_id', sa.BigInteger(), nullable=True),
    sa.Column('src_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('payload_relpath', sa.String(length=512), nullable=True),
    sa.Column('region_x', sa.Integer(), nullable=True),
    sa.Column('region_y', sa.Integer(), nullable=True),
    sa.Column('region_w', sa.Integer(), nullable=True),
    sa.Column('region_h', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('finished_at', mysql.DATETIME(fsp=0), nullable=True),
    sa.ForeignKeyConstraint(['src_asset_id'], ['eink_asset.id'], name=op.f('fk_device_jobs_src_asset_id_eink_asset'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['src_upload_id'], ['uploads.id'], name=op.f('fk_device_jobs_src_upload_id_uploads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_device_jobs_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_jobs')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('device_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_djob_dev_status', ['device_id', 'status'], unique=False)
        batch_op.create_index('idx_djob_type_status', ['job_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_jobs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_jobs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('eink_device', schema=None) as batch_op:
        batch_op.drop_constraint('uq_eink_device_user_device', type_='unique')
        batch_op.create_unique_constraint('uq_eink_device_user_device', ['user_no', 'device_id'])
        batch_op.create_index(batch_op.f('ix_eink_device_user_no'), ['user_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_device_user_userid'), ['user_userid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eink_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eink_device_user_userid'))
        batch_op.drop_index(batch_op.f('ix_eink_device_user_no'))
        batch_op.drop_constraint('uq_eink_device_user_device', type_='unique')
        batch_op.create_unique_constraint('uq_eink_device_user_device', ['device_id'])

    with op.batch_alter_table('device_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_jobs_device_id'))
        batch_op.drop_index('idx_djob_type_status')
        batch_op.drop_index('idx_djob_dev_status')

    op.drop_table('device_jobs')
    with op.batch_alter_table('upload_approval_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_approval_steps_upload_id'))
        batch_op.drop_index('idx_uapproval_upload')

    op.drop_table('upload_approval_steps')
    with op.batch_alter_table('sign_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sign_slots_upload_id'))
        batch_op.drop_index('idx_signslot_user')
        batch_op.drop_index('idx_signslot_upload')

    op.drop_table('sign_slots')
    # ### end Alembic commands ###
