"""empty message

Revision ID: 6703f2f7ad34
Revises: d107e3d82c2f
Create Date: 2025-12-15 20:19:29.553412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6703f2f7ad34'
down_revision = 'd107e3d82c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_info_id', sa.BigInteger(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('orig_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_relpath', sa.String(length=500), nullable=False),
    sa.Column('converted_pdf_relpath', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('source_ext', sa.String(length=16), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['document_info_id'], ['document_infos.id'], name=op.f('fk_document_attachments_document_info_id_document_infos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_attachments')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('document_attachments', schema=None) as batch_op:
        batch_op.create_index('idx_docatt_doc_order', ['document_info_id', 'order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_attachments_document_info_id'), ['document_info_id'], unique=False)

    op.create_table('document_device_page_map',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_info_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['document_info_id'], ['document_infos.id'], name=op.f('fk_document_device_page_map_document_info_id_document_infos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_device_page_map')),
    sa.UniqueConstraint('document_info_id', 'device_id', name='uq_docdev_doc_device'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('document_device_page_map', schema=None) as batch_op:
        batch_op.create_index('idx_docdev_doc', ['document_info_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_device_page_map_document_info_id'), ['document_info_id'], unique=False)

    op.create_table('document_page_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_info_id', sa.BigInteger(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('normalized_png_relpath', sa.String(length=500), nullable=True),
    sa.Column('normalized_bmp_relpath', sa.String(length=500), nullable=True),
    sa.Column('signed_png_relpath', sa.String(length=500), nullable=True),
    sa.Column('signed_bmp_relpath', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['document_info_id'], ['document_infos.id'], name=op.f('fk_document_page_assets_document_info_id_document_infos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_page_assets')),
    sa.UniqueConstraint('document_info_id', 'page_no', name='uq_docpage_doc_page'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('document_page_assets', schema=None) as batch_op:
        batch_op.create_index('idx_docpage_doc', ['document_info_id', 'page_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_page_assets_document_info_id'), ['document_info_id'], unique=False)

    with op.batch_alter_table('document_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('norm_canvas_w', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('norm_canvas_h', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('source_ext', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('source_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fit_mode', sa.Enum('fit', 'fill', 'percent', name='doc_fit_mode'), nullable=True))
        batch_op.add_column(sa.Column('normalized_pdf_relpath', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('normalized_dir_relpath', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('normalized_front_png_relpath', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('normalized_front_bmp_relpath', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('signed_front_png_relpath', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('signed_front_bmp_relpath', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('bundle_pdf_relpath', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('approved_bundle_pdf_relpath', sa.String(length=500), nullable=True))
        batch_op.drop_column('width')
        batch_op.drop_column('height')
        batch_op.drop_column('scale')
        batch_op.drop_column('mode')
        batch_op.drop_column('pages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mode', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('scale', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('width', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('approved_bundle_pdf_relpath')
        batch_op.drop_column('bundle_pdf_relpath')
        batch_op.drop_column('signed_front_bmp_relpath')
        batch_op.drop_column('signed_front_png_relpath')
        batch_op.drop_column('normalized_front_bmp_relpath')
        batch_op.drop_column('normalized_front_png_relpath')
        batch_op.drop_column('normalized_dir_relpath')
        batch_op.drop_column('normalized_pdf_relpath')
        batch_op.drop_column('fit_mode')
        batch_op.drop_column('source_pages')
        batch_op.drop_column('source_ext')
        batch_op.drop_column('norm_canvas_h')
        batch_op.drop_column('norm_canvas_w')

    with op.batch_alter_table('document_page_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_page_assets_document_info_id'))
        batch_op.drop_index('idx_docpage_doc')

    op.drop_table('document_page_assets')
    with op.batch_alter_table('document_device_page_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_device_page_map_document_info_id'))
        batch_op.drop_index('idx_docdev_doc')

    op.drop_table('document_device_page_map')
    with op.batch_alter_table('document_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_attachments_document_info_id'))
        batch_op.drop_index('idx_docatt_doc_order')

    op.drop_table('document_attachments')
    # ### end Alembic commands ###
