"""empty message

Revision ID: 6a7f30f42bc5
Revises: e15c5c33cd35
Create Date: 2025-12-17 10:31:43.217094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a7f30f42bc5'
down_revision = 'e15c5c33cd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_approval_steps', schema=None) as batch_op:
        batch_op.drop_column('step_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_approval_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_type', mysql.ENUM('작성', '검토', '승인'), nullable=False))

    # ### end Alembic commands ###
