"""empty message

Revision ID: 745034d3a8ef
Revises: fabc9c6ffb24
Create Date: 2025-01-15 11:34:35.670447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745034d3a8ef'
down_revision = 'fabc9c6ffb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('YoutubeURL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_video', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('YoutubeURL', schema=None) as batch_op:
        batch_op.drop_column('title_video')

    # ### end Alembic commands ###
