"""empty message

Revision ID: 7a3113c84e97
Revises: e333fd47cbc9
Create Date: 2025-01-20 15:50:07.274183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3113c84e97'
down_revision = 'e333fd47cbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NaverData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('sizeweight', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sizeheight', sa.String(length=100), nullable=False))
        batch_op.drop_column('summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NaverData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('sizeheight')
        batch_op.drop_column('sizeweight')
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
