"""empty message

Revision ID: 872cf49fa005
Revises: 0952e06d17c1
Create Date: 2025-02-10 16:39:00.907591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872cf49fa005'
down_revision = '0952e06d17c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_1', sa.String(length=255), nullable=True),
    sa.Column('file_2', sa.String(length=255), nullable=True),
    sa.Column('file_3', sa.String(length=255), nullable=True),
    sa.Column('file_4', sa.String(length=255), nullable=True),
    sa.Column('file_5', sa.String(length=255), nullable=True),
    sa.Column('file_6', sa.String(length=255), nullable=True),
    sa.Column('file_7', sa.String(length=255), nullable=True),
    sa.Column('file_8', sa.String(length=255), nullable=True),
    sa.Column('file_9', sa.String(length=255), nullable=True),
    sa.Column('file_10', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_file_uploads_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_uploads'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
