"""empty message

Revision ID: 8dfc1a66b14b
Revises: 0d851f75b114
Create Date: 2025-01-22 09:11:38.114408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfc1a66b14b'
down_revision = '0d851f75b114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ImageData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmp_file', sa.String(length=200), nullable=False))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ImageData', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('bmp_file')

    # ### end Alembic commands ###
