"""empty message

Revision ID: 8fa2d3c58015
Revises: c3170af5d6f1
Create Date: 2025-02-10 10:21:27.763382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa2d3c58015'
down_revision = 'c3170af5d6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('namecard', schema=None) as batch_op:
        batch_op.drop_constraint('fk_namecard_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_namecard_user_id_user'), 'user', ['user_id'], ['userid'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('namecard', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_namecard_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_namecard_user_id_user', 'user', ['user_id'], ['no'], ondelete='CASCADE')

    # ### end Alembic commands ###
