"""empty message

Revision ID: 98c3bfa3e111
Revises: 6703f2f7ad34
Create Date: 2025-12-16 08:57:20.849472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c3bfa3e111'
down_revision = '6703f2f7ad34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('route_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_infos_route_id'), ['route_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_infos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_infos_route_id'))
        batch_op.drop_column('route_id')
        batch_op.drop_column('mode')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('pages')

    # ### end Alembic commands ###
