"""empty message

Revision ID: 998c57362e63
Revises: 8dfc1a66b14b
Create Date: 2025-02-04 16:20:41.765152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998c57362e63'
down_revision = '8dfc1a66b14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userimage', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('blood', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('healthy', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('security', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('security')
        batch_op.drop_column('address')
        batch_op.drop_column('age')
        batch_op.drop_column('healthy')
        batch_op.drop_column('blood')
        batch_op.drop_column('position')
        batch_op.drop_column('department')
        batch_op.drop_column('company')
        batch_op.drop_column('userimage')

    # ### end Alembic commands ###
