"""empty message

Revision ID: 9b2000c85ef0
Revises: 28cfda66f072
Create Date: 2025-10-10 12:42:01.322124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b2000c85ef0'
down_revision = '28cfda66f072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_routes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.no'], name=op.f('fk_approval_routes_created_by_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_routes')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sign_layouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('canvas_w', sa.Integer(), nullable=False),
    sa.Column('canvas_h', sa.Integer(), nullable=False),
    sa.Column('parent_x', sa.Integer(), nullable=False),
    sa.Column('parent_y', sa.Integer(), nullable=False),
    sa.Column('parent_w', sa.Integer(), nullable=False),
    sa.Column('parent_h', sa.Integer(), nullable=False),
    sa.Column('tpl_json', sa.JSON(), nullable=False),
    sa.Column('slots_json', sa.JSON(), nullable=False),
    sa.Column('layers_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.no'], name=op.f('fk_sign_layouts_owner_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sign_layouts')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('approval_route_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('author', 'review', 'approve', 'review2', 'approve2', name='approval_role'), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('assignee_group_id', sa.Integer(), nullable=True),
    sa.Column('sign_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['user.no'], name=op.f('fk_approval_route_steps_assignee_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['approval_routes.id'], name=op.f('fk_approval_route_steps_route_id_approval_routes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_route_steps')),
    sa.UniqueConstraint('route_id', 'step_order', name='uq_route_steporder'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('uploads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('orig_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('target_dir', sa.Enum('uploads', 'proceed', name='upload_target_dir'), nullable=False),
    sa.Column('need_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'approved', 'rejected', name='approval_status'), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('scale', sa.String(length=20), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('rotate', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.BigInteger(), nullable=True),
    sa.Column('sign_layout_id', sa.BigInteger(), nullable=True),
    sa.Column('route_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('layout_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['approval_routes.id'], name=op.f('fk_uploads_route_id_approval_routes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sign_layout_id'], ['sign_layouts.id'], name=op.f('fk_uploads_sign_layout_id_sign_layouts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_uploads_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploads')
    op.drop_table('approval_route_steps')
    op.drop_table('sign_layouts')
    op.drop_table('approval_routes')
    # ### end Alembic commands ###
