"""empty message

Revision ID: 9f1a868c55b5
Revises: a426b0085aee
Create Date: 2025-12-22 14:58:07.428673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1a868c55b5'
down_revision = 'a426b0085aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eink_board_binding', schema=None) as batch_op:
        batch_op.create_index('idx_eink_binding_board_time', ['board_id', 'bound_at', 'unbound_at'], unique=False)
        batch_op.create_index('idx_eink_binding_device_time', ['device_id', 'bound_at', 'unbound_at'], unique=False)
        batch_op.create_unique_constraint('uq_eink_binding_device_active', ['device_id', 'active'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eink_board_binding', schema=None) as batch_op:
        batch_op.drop_constraint('uq_eink_binding_device_active', type_='unique')
        batch_op.drop_index('idx_eink_binding_device_time')
        batch_op.drop_index('idx_eink_binding_board_time')

    # ### end Alembic commands ###
