"""empty message

Revision ID: a426b0085aee
Revises: 3c8c714ab992
Create Date: 2025-12-22 09:53:59.875693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a426b0085aee'
down_revision = '3c8c714ab992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eink_company',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eink_company')),
    sa.UniqueConstraint('code', name='uq_eink_company_code'),
    sa.UniqueConstraint('name', name='uq_eink_company_name'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('eink_building',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['eink_company.id'], name=op.f('fk_eink_building_company_id_eink_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eink_building')),
    sa.UniqueConstraint('company_id', 'name', name='uq_eink_building_company_name'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eink_building', schema=None) as batch_op:
        batch_op.create_index('idx_eink_building_company', ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_building_company_id'), ['company_id'], unique=False)

    op.create_table('eink_board',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('floor_no', sa.Integer(), nullable=False),
    sa.Column('board_no', sa.Integer(), nullable=False),
    sa.Column('board_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location_desc', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['eink_building.id'], name=op.f('fk_eink_board_building_id_eink_building'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eink_board')),
    sa.UniqueConstraint('board_code', name='uq_eink_board_code'),
    sa.UniqueConstraint('building_id', 'floor_no', 'board_no', name='uq_eink_board_bld_floor_no'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eink_board', schema=None) as batch_op:
        batch_op.create_index('idx_eink_board_building_floor', ['building_id', 'floor_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_board_building_id'), ['building_id'], unique=False)

    op.create_table('eink_board_binding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('bound_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.Column('unbound_at', mysql.DATETIME(fsp=0), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('bound_by_user_no', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), sa.Computed('IF(unbound_at IS NULL, 1, 0)', persisted=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=0), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['eink_board.id'], name=op.f('fk_eink_board_binding_board_id_eink_board'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bound_by_user_no'], ['user.no'], name=op.f('fk_eink_board_binding_bound_by_user_no_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['eink_device.id'], name=op.f('fk_eink_board_binding_device_id_eink_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eink_board_binding')),
    sa.UniqueConstraint('board_id', 'active', name='uq_eink_binding_board_active'),
    sa.UniqueConstraint('device_id', 'active', name='uq_eink_binding_device_active'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eink_board_binding', schema=None) as batch_op:
        batch_op.create_index('idx_eink_binding_board_time', ['board_id', 'bound_at', 'unbound_at'], unique=False)
        batch_op.create_index('idx_eink_binding_device_time', ['device_id', 'bound_at', 'unbound_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_board_binding_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_board_binding_bound_by_user_no'), ['bound_by_user_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_board_binding_device_id'), ['device_id'], unique=False)

    with op.batch_alter_table('eink_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.BigInteger(), nullable=True))
        batch_op.alter_column('user_no',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_index('idx_eink_device_user_lastseen')
        batch_op.drop_index('uq_eink_device_user_device')
        batch_op.create_index('idx_eink_device_company_lastseen', ['company_id', 'last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_eink_device_company_id'), ['company_id'], unique=False)
        batch_op.create_unique_constraint('uq_eink_device_device_id', ['device_id'])
        batch_op.drop_constraint('fk_eink_device_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_eink_device_company_id_eink_company'), 'eink_company', ['company_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_eink_device_user_no_user'), 'user', ['user_no'], ['no'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eink_device', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_eink_device_user_no_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_eink_device_company_id_eink_company'), type_='foreignkey')
        batch_op.create_foreign_key('fk_eink_device_user', 'user', ['user_no'], ['no'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_eink_device_device_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_eink_device_company_id'))
        batch_op.drop_index('idx_eink_device_company_lastseen')
        batch_op.create_index('uq_eink_device_user_device', ['user_no', 'device_id'], unique=True)
        batch_op.create_index('idx_eink_device_user_lastseen', ['user_no', 'last_seen'], unique=False)
        batch_op.alter_column('user_no',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('eink_board_binding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eink_board_binding_device_id'))
        batch_op.drop_index(batch_op.f('ix_eink_board_binding_bound_by_user_no'))
        batch_op.drop_index(batch_op.f('ix_eink_board_binding_board_id'))
        batch_op.drop_index('idx_eink_binding_device_time')
        batch_op.drop_index('idx_eink_binding_board_time')

    op.drop_table('eink_board_binding')
    with op.batch_alter_table('eink_board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eink_board_building_id'))
        batch_op.drop_index('idx_eink_board_building_floor')

    op.drop_table('eink_board')
    with op.batch_alter_table('eink_building', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eink_building_company_id'))
        batch_op.drop_index('idx_eink_building_company')

    op.drop_table('eink_building')
    op.drop_table('eink_company')
    # ### end Alembic commands ###
