"""empty message

Revision ID: b76fcf09845d
Revises: 6a7f30f42bc5
Create Date: 2025-12-17 11:40:45.398682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76fcf09845d'
down_revision = '6a7f30f42bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_approval_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_type', sa.Enum('작성', '검토', '승인', name='approval_step_type'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_approval_steps', schema=None) as batch_op:
        batch_op.drop_column('step_type')

    # ### end Alembic commands ###
