"""empty message

Revision ID: c07a2f31a2c8
Revises: d4e98c9f3f5e
Create Date: 2025-10-10 16:50:43.651262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07a2f31a2c8'
down_revision = 'd4e98c9f3f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_target_dir'), ['target_dir'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_target_dir'))
        batch_op.drop_index(batch_op.f('ix_uploads_status'))

    with op.batch_alter_table('approval_routes', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
