"""empty message

Revision ID: c3170af5d6f1
Revises: 356aeb3a305d
Create Date: 2025-02-10 09:57:05.232661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3170af5d6f1'
down_revision = '356aeb3a305d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_photo', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('com_address', sa.String(length=500), nullable=True),
    sa.Column('tel_rep', sa.String(length=100), nullable=True),
    sa.Column('tel_dir', sa.String(length=100), nullable=True),
    sa.Column('fax', sa.String(length=100), nullable=True),
    sa.Column('homepage', sa.String(length=300), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.no'], name=op.f('fk_namecard_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_namecard'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('namecard')
    # ### end Alembic commands ###
