"""empty message

Revision ID: d107e3d82c2f
Revises: d0f109f6dfa4
Create Date: 2025-12-12 15:41:42.493681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd107e3d82c2f'
down_revision = 'd0f109f6dfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###

    # 1) DocumentInfo 에서 approval_routes FK/컬럼 제거
    with op.batch_alter_table('document_infos', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_document_infos_route_id_approval_routes',
            type_='foreignkey'
        )
        batch_op.drop_column('route_id')

    # 2) EInkAsset 에서 approval_routes FK/컬럼 제거 + approval_snapshot_json 추가
    with op.batch_alter_table('eink_asset', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('approval_snapshot_json', sa.JSON(), nullable=True)
        )
        batch_op.drop_constraint(
            'fk_eink_asset_route_id_approval_routes',
            type_='foreignkey'
        )
        batch_op.drop_column('route_id')

    # 3) 자식 테이블(approval_route_steps) 먼저 삭제
    op.drop_table('approval_route_steps')

    # 4) 부모 테이블(approval_routes) 삭제
    op.drop_table('approval_routes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###

    # 1) approval_routes 테이블 복원
    op.create_table(
        'approval_routes',
        sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['user.no'],
            name='fk_approval_routes_created_by_user',
            ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    with op.batch_alter_table('approval_routes', schema=None) as batch_op:
        batch_op.create_index(
            'ix_approval_routes_created_by',
            ['created_by'],
            unique=False
        )

    # 2) approval_route_steps 테이블 복원
    op.create_table(
        'approval_route_steps',
        sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column('route_id', mysql.BIGINT(), autoincrement=False, nullable=False),
        sa.Column('step_order', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'role',
            mysql.ENUM('author', 'review', 'approve', 'review2', 'approve2'),
            nullable=False
        ),
        sa.Column('assignee_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('assignee_group_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('sign_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('assignee_userid_snapshot', mysql.VARCHAR(length=150), nullable=True),
        sa.Column('assignee_username_snapshot', mysql.VARCHAR(length=150), nullable=True),
        sa.Column('assignee_department_snapshot', mysql.VARCHAR(length=150), nullable=True),
        sa.Column('assignee_position_snapshot', mysql.VARCHAR(length=150), nullable=True),
        sa.Column('assignee_photo_1_snapshot', mysql.VARCHAR(length=500), nullable=True),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ['assignee_user_id'],
            ['user.no'],
            name='fk_approval_route_steps_assignee_user_id_user',
            ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['route_id'],
            ['approval_routes.id'],
            name='fk_approval_route_steps_route_id_approval_routes',
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    with op.batch_alter_table('approval_route_steps', schema=None) as batch_op:
        batch_op.create_index(
            'uq_route_steporder',
            ['route_id', 'step_order'],
            unique=True
        )
        batch_op.create_index(
            'ix_approval_route_steps_route_id',
            ['route_id'],
            unique=False
        )
        batch_op.create_index(
            'ix_approval_route_steps_assignee_user_id',
            ['assignee_user_id'],
            unique=False
        )

    # 3) document_infos 에 route_id / FK 복원
    with op.batch_alter_table('document_infos', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('route_id', mysql.BIGINT(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            'fk_document_infos_route_id_approval_routes',
            'approval_routes',
            ['route_id'],
            ['id'],
            ondelete='SET NULL'
        )

    # 4) eink_asset 에 route_id / FK 복원 + approval_snapshot_json 제거
    with op.batch_alter_table('eink_asset', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('route_id', mysql.BIGINT(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            'fk_eink_asset_route_id_approval_routes',
            'approval_routes',
            ['route_id'],
            ['id'],
            ondelete='SET NULL'
        )
        batch_op.drop_column('approval_snapshot_json')

    # ### end Alembic commands ###
