"""empty message

Revision ID: e333fd47cbc9
Revises: f5c37ddf56a9
Create Date: 2025-01-20 10:11:55.178308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e333fd47cbc9'
down_revision = 'f5c37ddf56a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BlogData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star_name', sa.String(length=100), nullable=False),
    sa.Column('type_blog', sa.String(length=100), nullable=False),
    sa.Column('title_blog', sa.String(length=300), nullable=False),
    sa.Column('json_file', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('update_date', sa.String(length=150), nullable=False),
    sa.Column('view_count', sa.String(length=100), nullable=True),
    sa.Column('favorite_count', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_BlogData'))
    )
    op.create_table('NewsData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star_name', sa.String(length=100), nullable=False),
    sa.Column('type_news', sa.String(length=100), nullable=False),
    sa.Column('title_new', sa.String(length=300), nullable=False),
    sa.Column('json_file', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('origin_url', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('update_date', sa.String(length=150), nullable=False),
    sa.Column('view_count', sa.String(length=100), nullable=True),
    sa.Column('favorite_count', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_NewsData'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NewsData')
    op.drop_table('BlogData')
    # ### end Alembic commands ###
