"""empty message

Revision ID: f46d7e27b421
Revises: 5edbb8d06335
Create Date: 2025-03-10 13:27:46.017816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46d7e27b421'
down_revision = '5edbb8d06335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ImageData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_word', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('bmp_42_mono', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bmp_42_3color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bmp_37_4color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bmp_29_mono', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bmp_29_3color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bmp_29_4color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bmp_file_1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bmp_file_2', sa.String(length=200), nullable=True))
        batch_op.drop_column('star_name')
        batch_op.drop_column('bmp_file')

    with op.batch_alter_table('welcomedata', schema=None) as batch_op:
        batch_op.drop_column('qrcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('welcomedata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qrcode', sa.VARCHAR(length=150), nullable=True))

    with op.batch_alter_table('ImageData', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmp_file', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('star_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('bmp_file_2')
        batch_op.drop_column('bmp_file_1')
        batch_op.drop_column('bmp_29_4color')
        batch_op.drop_column('bmp_29_3color')
        batch_op.drop_column('bmp_29_mono')
        batch_op.drop_column('bmp_37_4color')
        batch_op.drop_column('bmp_42_3color')
        batch_op.drop_column('bmp_42_mono')
        batch_op.drop_column('key_word')

    # ### end Alembic commands ###
