"""empty message

Revision ID: f5c37ddf56a9
Revises: 745034d3a8ef
Create Date: 2025-01-17 16:10:43.959329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c37ddf56a9'
down_revision = '745034d3a8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NaverData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star_name', sa.String(length=100), nullable=False),
    sa.Column('type_image', sa.String(length=100), nullable=False),
    sa.Column('title_image', sa.String(length=300), nullable=False),
    sa.Column('json_file', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('update_date', sa.String(length=150), nullable=False),
    sa.Column('view_count', sa.String(length=100), nullable=True),
    sa.Column('favorite_count', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_NaverData'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NaverData')
    # ### end Alembic commands ###
