"""empty message

Revision ID: ff4a7a06222e
Revises: 4efaa1a98ef4
Create Date: 2025-10-13 16:48:11.859458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4a7a06222e'
down_revision = '4efaa1a98ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_slots', schema=None) as batch_op:
        batch_op.create_index('idx_signslot_upload_slot', ['upload_id', 'slot_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sign_slots', schema=None) as batch_op:
        batch_op.drop_index('idx_signslot_upload_slot')

    # ### end Alembic commands ###
